#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(u8)]
pub enum OpCode {
    Return,
    Constant,
    Add,
    Subtract,
    Multiply,
    Divide,
    Negate,
    True,
    False,
    Null,
    Not,
    Equal,
    Greater,
    Less,
    Pop,
    DefineGlobal,
    GetGlobal,
    SetGlobal,
    GetLocal,
    SetLocal,
    Jump,
    JumpIfFalse,
    Loop,
    Call,
    Vector,
    HashMap,
    GetIndex,
    SetIndex,
    Namespace,
    Closure,
    GetUpvalue,
    SetUpvalue,
    CloseUpvalue,
}

impl From<u8> for OpCode {
    fn from(value: u8) -> Self {
        match value {
            0 => OpCode::Return,
            1 => OpCode::Constant,
            2 => OpCode::Add,
            3 => OpCode::Subtract,
            4 => OpCode::Multiply,
            5 => OpCode::Divide,
            6 => OpCode::Negate,
            7 => OpCode::True,
            8 => OpCode::False,
            9 => OpCode::Null,
            10 => OpCode::Not,
            11 => OpCode::Equal,
            12 => OpCode::Greater,
            13 => OpCode::Less,
            14 => OpCode::Pop,
            15 => OpCode::DefineGlobal,
            16 => OpCode::GetGlobal,
            17 => OpCode::SetGlobal,
            18 => OpCode::GetLocal,
            19 => OpCode::SetLocal,
            20 => OpCode::Jump,
            21 => OpCode::JumpIfFalse,
            22 => OpCode::Loop,
            23 => OpCode::Call,
            24 => OpCode::Vector,
            25 => OpCode::HashMap,
            26 => OpCode::GetIndex,
            27 => OpCode::SetIndex,
            28 => OpCode::Namespace,
            29 => OpCode::Closure,
            30 => OpCode::GetUpvalue,
            31 => OpCode::SetUpvalue,
            32 => OpCode::CloseUpvalue,
            _ => panic!("Unknown opcode: {}", value),
        }
    }
}
